services:
  # node:
  #   image: node:lts
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   stdin_open: true
  #   tty: true
  #   command:
  #     - /bin/bash
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - ~/bootcamp/class-docker-db:/var/lib/mysql
      - .:/app
    working_dir: /app
